export const alphabetItems = [
  { letter: 'A', word: 'Apple', picture: '🍎', color: '#fee2e2' },
  { letter: 'B', word: 'Ball', picture: '🏀', color: '#ffedd5' },
  { letter: 'C', word: 'Cat', picture: '🐱', color: '#fef3c7' },
  { letter: 'D', word: 'Dog', picture: '🐶', color: '#dcfce7' },
  { letter: 'E', word: 'Elephant', picture: '🐘', color: '#dbeafe' },
  { letter: 'F', word: 'Fish', picture: '🐟', color: '#cffafe' },
  { letter: 'G', word: 'Grapes', picture: '🍇', color: '#ede9fe' },
  { letter: 'H', word: 'Hat', picture: '🎩', color: '#fae8ff' },
  { letter: 'I', word: 'Ice cream', picture: '🍦', color: '#fce7f3' },
  { letter: 'J', word: 'Jug', picture: '🏺', color: '#e0f2fe' },
  { letter: 'K', word: 'Kite', picture: '🪁', color: '#fef9c3' },
  { letter: 'L', word: 'Lion', picture: '🦁', color: '#fed7aa' },
  { letter: 'M', word: 'Mango', picture: '🥭', color: '#ffedd5' },
  { letter: 'N', word: 'Nest', picture: '🪺', color: '#ecfccb' },
  { letter: 'O', word: 'Orange', picture: '🍊', color: '#fed7aa' },
  { letter: 'P', word: 'Parrot', picture: '🦜', color: '#bbf7d0' },
  { letter: 'Q', word: 'Queen', picture: '👑', color: '#fef3c7' },
  { letter: 'R', word: 'Rabbit', picture: '🐰', color: '#fbcfe8' },
  { letter: 'S', word: 'Sun', picture: '☀️', color: '#fde68a' },
  { letter: 'T', word: 'Tiger', picture: '🐯', color: '#fed7aa' },
  { letter: 'U', word: 'Umbrella', picture: '☂️', color: '#ddd6fe' },
  { letter: 'V', word: 'Van', picture: '🚐', color: '#bfdbfe' },
  { letter: 'W', word: 'Watch', picture: '⌚', color: '#e5e7eb' },
  { letter: 'X', word: 'Xylophone', picture: '🎵', color: '#f5d0fe' },
  { letter: 'Y', word: 'Yacht', picture: '⛵', color: '#bae6fd' },
  { letter: 'Z', word: 'Zebra', picture: '🦓', color: '#e7e5e4' },
] as const;

export type AlphabetItem = (typeof alphabetItems)[number];
